version: "2"
services:

  db:
    image: postgres
    ports:
      - "5432:5432"

  django:
    container_name: django
    hostname: django
    env_file:
      - docker/dev.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    ports:
      - "8000:8000"
    command: ["./docker/wait-for-it.sh", "db:5432", "--", "sh", "/code/docker/dev/django/container-start.sh"]
    depends_on:
      - "db"

  nodejs:
    container_name: nodejs
    hostname: nodejs
    build:
      context: ./
      dockerfile: docker/dev/nodejs/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "4200:4200"
    depends_on:
      - django
