# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT goodgames.wsgi

beta_settings:
    cloud_sql_instances: goodgames-185922:us-central1:goodgames-db

skip_files:
- scripts/

runtime_config:
  python_version: 2
# [END runtime]